### ISSUE TITLE
Review file structure

### ISSUE THREAD

**Issue by amyjsdavis** [trias-project/risk-modelling-and-mapping#1]

**Comment by damianooldoni** [comment]
1. It's a little difficult to review structure with not so many files actually. However, it is quite ok as it comes from the Cookie Cutter project :+1: 
2. I see that you are using Python! Nice. And good to know too. This will make impossible to put your future functions in `trias` R package. But I understand that Python is a very powerful programming language, and for computationally demanding steps way faster than R. So, no issues on it if you need Python's speed :+1: 
3. I see that there is a standard R `.gitignore` file. If you use Python, maybe you can update it to something like this: [python gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore).
4. The only code I see up to now refers to raw data processing. But there is no raw data still. Are they too big to be put here? Moreover, if you use data coming from other TriAS repositories, please do not copy paste them, but just by reading them via something like this
```r
import urllib
raw_data = urllib.urlopen(target_url).read()
```

**Comment by amyjsdavis** [comment]
I will only use R code for the TrIAS modelling. I just used python to set up the file structure using cookie cutter. Indeed raw data is too big.

**Comment by damianooldoni** [comment]
As said before, it is difficult at this stage to make a in-depth review. Still, I suppose we would like to have some pipelines in order to follow the workflow. For us and  for others as well. So, maybe adding `notebooks` subdirectory as suggested by cookiecutter?

If you have other solutions in mind, you are very welcome to share them!

**Comment by damianooldoni** [comment]
Forget notebooks directory if you are not using Python then.
Typically, we make Rmd files in `src` and put functions in trias package. 
At this stage of work,  you can put R file with functions in `src` as well, and then I will move them to TrIAS package and I will apply the needed changes to the pipelines (aka Rmd files).

**Comment by damianooldoni** [comment]
> I just used python to set up the file structure using cookie cutter.
The file structure can be set up without using Python files.

FYI, from a [stackoverflow post](https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep/7229996#7229996):
> Git cannot add a completely empty directory. People who want to track empty directories in Git have created the convention of putting files called `.gitkeep` in these directories. The file could be called anything; Git assigns no special significance to this name.

Files starting with a point are hidden files so, they don't bother you too much. Still, if you plan to add files very soon, forget this approach and leave everything as it is now. You can remove the Python files meanwhile you add R files.

**Comment by damianooldoni** [comment]
I think this issue can be closed now.
