### ISSUE TITLE
Files not present in repo: syncing your working folder with this repo

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/risk-modelling-and-mapping#12]
A question: where is the `pra_mammals.csv` file you are using in https://github.com/trias-project/risk-modelling-and-mapping/blob/master/src/global_download.Rmd#L43

It seems you are working on a local directory, `././modelling` which is not synced to this repository. This should be avoided as it makes working with GitHub way less powerful than it could be. And the files in this repo become easily outdated.

Please, contact me or @peterdesmet if you have problems performing the "git jump" :jump
Notice that if you are not confident to share some files as they are not ready for being shared, you can list them in the .gitignore and they will not be pushed to remote (= this repo).

**Comment by amyjsdavis** [comment]
I added pra.mammals.csv to the repo.

**Comment by damianooldoni** [comment]
Nice! However, please consider to use the link to raw data instead of the html interface to it. Otherwise you get something like this in `taxa`, which will make your code crash:

![image](https://user-images.githubusercontent.com/33662631/95996350-db941200-0e32-11eb-8b9a-e36ddce72002.png)

So, the link in [global_download.Rmd#L43](https://github.com/trias-project/risk-modelling-and-mapping/blob/master/src/global_download.Rmd#L43) should be replaced by this:

```r
taxa_input_file <- "https://raw.githubusercontent.com/trias-project/risk-modelling-and-mapping/master/data/external/PRA/pra_mammals.csv"
```

Notice the `raw.githubusercontent.com` at the beginning and the absence of `blob` in the middle.

**Comment by amyjsdavis** [comment]
thanks Damiano! I changed it.
